//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpaces
    {
        public ParkingSpaces()
        {
            this.Reservations = new HashSet<Reservations>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int SpaceID { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual ICollection<Reservations> Reservations { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
